# Generated by Django 5.1.6 on 2025-08-11 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(default='Описание', verbose_name='Описание')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('year_of_publish', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)], verbose_name='Год публикации')),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='Кол-во страниц')),
                ('binding', models.CharField(choices=[('hard', 'Твёрдый переплёт'), ('soft', 'Мягкий переплёт')], default='hard', max_length=10, verbose_name='Переплёт')),
                ('in_stock', models.PositiveIntegerField(default=0, verbose_name='Кол-во в магазине')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title'],
            },
        ),
    ]
