# Generated by Django 5.1.6 on 2025-08-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_cart_category_alter_book_unit_price_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bookshop.category', verbose_name='Категория'),
        ),
    ]
