# Generated by Django 5.1.6 on 2025-09-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0006_cart_user_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='Фото'),
        ),
    ]
