version: "3.9"

services:
  db:
    image: postgres:17
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: celery_worker
    command: celery -A coworking worker -l info
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A coworking beat -l info
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
