# Generated by Django 5.1.6 on 2025-08-11 12:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('room_type', models.CharField(choices=[('standard', 'Стандартное место'), ('vip', 'VIP-кабинка'), ('meeting', 'Переговорная')], default='standard', max_length=20, verbose_name='Тип помещения')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('tariff_type', models.CharField(choices=[('hourly', 'Почасовой'), ('daily', 'Дневной'), ('weekly', 'Недельный'), ('monthly', 'Месячный')], max_length=20, verbose_name='Тип тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('available_for_vip', models.BooleanField(default=True, verbose_name='Доступен для VIP')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('start_time', models.DateTimeField(verbose_name='Начало брони')),
                ('end_time', models.DateTimeField(verbose_name='Окончание брони')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.room', verbose_name='Помещение')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
