# Generated by Django 5.1.6 on 2025-09-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_subscription_remove_booking_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subscription_images/', verbose_name='Фото'),
        ),
    ]
