# Generated by Django 5.1.6 on 2025-08-11 10:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('discount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Процент скидки')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена за 1 ед.')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('promotion', models.ManyToManyField(blank=True, related_name='coffees', to='coffeeshop.promotion')),
            ],
            options={
                'verbose_name': 'Кофе',
                'verbose_name_plural': 'Кофе',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена за 1 ед.')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('in_stock', models.PositiveIntegerField(default=0, verbose_name='Кол-во в магазине')),
                ('promotion', models.ManyToManyField(blank=True, related_name='bakeries', to='coffeeshop.promotion')),
            ],
            options={
                'verbose_name': 'Выпечка',
                'verbose_name_plural': 'Выпечка',
                'ordering': ['title'],
            },
        ),
    ]
