# Generated by Django 5.1.6 on 2025-09-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bakery_images/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffee_images/', verbose_name='Фото'),
        ),
    ]
